##
# .rubocop.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'config/initializers/devise.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/admin/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
