##
# .rubocop.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'config/initializers/devise.rb'
    - 'config/environments/*'
    - 'app/datatables/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/admin/*'
    - 'app/helpers/admin/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

Style/MixinUsage:
  Exclude:
    - 'spec/rails_helper.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/spec_helpers/shopify_dummy_data_helper.rb'